#!/usr/bin/env python3
import argparse
import json
from pathlib import Path


def parse_value(raw):
    if isinstance(raw, int):
        return raw
    if isinstance(raw, str):
        return int(raw, 0)
    raise ValueError(f"Unsupported value type: {type(raw)!r}")


def to_signed16(value):
    value &= 0xFFFF
    return value - 0x10000 if value & 0x8000 else value


def to_u32_hex(value):
    return f"0x{(value & 0xFFFFFFFF):08x}"


def s16_to_u32_signext(value):
    raw16 = value & 0xFFFF
    if raw16 & 0x8000:
        return 0xFFFF0000 | raw16
    return raw16


def row_chunks(values):
    return [values[i : i + 4] for i in range(0, 16, 4)]


def compute_expected(a_vals, b_vals):
    expected = []
    for row in range(4):
        for col in range(4):
            acc = 0
            for k in range(4):
                a_elem = to_signed16(a_vals[row * 4 + k])
                b_elem = to_signed16(b_vals[k * 4 + col])
                acc += (a_elem * b_elem) >> 10
            c16 = to_signed16(acc)
            expected.append(c16)
    return expected


def load_case(cases_path, case_name):
    data = json.loads(Path(cases_path).read_text(encoding="utf-8"))
    all_cases = data.get("cases", [])
    for case in all_cases:
        if case.get("name") == case_name:
            return case
    known = ", ".join(sorted(c.get("name", "") for c in all_cases))
    raise ValueError(f"Case '{case_name}' not found. Known cases: {known}")


def validate_matrix(name, values):
    if len(values) != 16:
        raise ValueError(f"{name} must contain exactly 16 elements, got {len(values)}")
    signed = [to_signed16(parse_value(v)) for v in values]
    return signed


def render_firmware(case_name, notes, a_vals, b_vals):
    a_u32 = [v & 0xFFFF for v in a_vals]
    b_u32 = [v & 0xFFFF for v in b_vals]

    def render_words(label, values):
        lines = [f"{label}:"]
        for row in row_chunks(values):
            words = ", ".join(to_u32_hex(v) for v in row)
            lines.append(f"    .word {words}")
        return "\n".join(lines)

    return f""".section .text
.global _start

_start:
    // Auto-generated by gen_case_firmware.py for case: {case_name}
    // {notes}
    // Copy matrix A words from firmware image to RAM buffer at 0x100.
    la   x5, a_init
    addi x6, x0, 0x100
    addi x7, x0, 16
copy_a:
    lw   x8, 0(x5)
    sw   x8, 0(x6)
    addi x5, x5, 4
    addi x6, x6, 4
    addi x7, x7, -1
    bne  x7, x0, copy_a

    // Copy matrix B words from firmware image to RAM buffer at 0x140.
    la   x5, b_init
    addi x6, x0, 0x140
    addi x7, x0, 16
copy_b:
    lw   x8, 0(x5)
    sw   x8, 0(x6)
    addi x5, x5, 4
    addi x6, x6, 4
    addi x7, x7, -1
    bne  x7, x0, copy_b

    // x1 = A base pointer (0x100), x2 = B base pointer (0x140)
    addi x1, x0, 0x100
    addi x2, x0, 0x140

    // custom matmul instruction
    // opcode=custom-0 (0001011), funct3=000, funct7=0101010, rd=x3, rs1=x1, rs2=x2
    .word 0x5420818b

    // load c00 from C base (0x200) and store to sentinel location 0x0
    lw   x4, 0x200(x0)
    sw   x4, 0(x0)

1:
    jal  x0, 1b

.section .rodata

{render_words("a_init", a_u32)}

{render_words("b_init", b_u32)}
"""


def main():
    parser = argparse.ArgumentParser(description="Generate firmware.S for a selected PCPI demo test case.")
    parser.add_argument("--cases", required=True, help="Path to cases.json")
    parser.add_argument("--case", required=True, help="Case name")
    parser.add_argument("--firmware-out", required=True, help="Output path for generated firmware.S")
    parser.add_argument("--meta-out", help="Optional output path for expected metadata JSON")
    args = parser.parse_args()

    case = load_case(args.cases, args.case)
    case_name = case["name"]
    notes = case.get("notes", "No notes.")
    a_vals = validate_matrix("a_q5_10", case["a_q5_10"])
    b_vals = validate_matrix("b_q5_10", case["b_q5_10"])
    expected = compute_expected(a_vals, b_vals)

    firmware_text = render_firmware(case_name, notes, a_vals, b_vals)
    firmware_out = Path(args.firmware_out)
    firmware_out.write_text(firmware_text, encoding="utf-8")

    if args.meta_out:
        meta = {
            "name": case_name,
            "notes": notes,
            "a_q5_10_s16": a_vals,
            "b_q5_10_s16": b_vals,
            "expected_c_q5_10_s16": expected,
            "expected_c_q5_10_u32_hex": [to_u32_hex(s16_to_u32_signext(v)) for v in expected],
            "expected_c00_u32_hex": to_u32_hex(s16_to_u32_signext(expected[0])),
        }
        meta_out = Path(args.meta_out)
        meta_out.parent.mkdir(parents=True, exist_ok=True)
        meta_out.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")

    print(f"Generated firmware for case '{case_name}' at {firmware_out}")


if __name__ == "__main__":
    main()
