#!/usr/bin/env python3
import argparse
import json
from pathlib import Path


def parse_value(raw):
    if isinstance(raw, int):
        return raw
    if isinstance(raw, str):
        return int(raw, 0)
    raise ValueError(f"Unsupported value type: {type(raw)!r}")


def to_u16(value):
    return value & 0xFFFF


def load_case(cases_path, case_name):
    data = json.loads(Path(cases_path).read_text(encoding="utf-8-sig"))
    for case in data.get("cases", []):
        if case.get("name") == case_name:
            return case
    known = ", ".join(sorted(c.get("name", "") for c in data.get("cases", [])))
    raise ValueError(f"Case '{case_name}' not found. Known cases: {known}")


def validate_case(case):
    dim = int(case["dim"])
    if dim <= 0:
        raise ValueError("dim must be positive")
    a_vals = [parse_value(v) for v in case["a_q5_10"]]
    b_vals = [parse_value(v) for v in case["b_q5_10"]]
    expected_len = dim * dim
    if len(a_vals) != expected_len:
        raise ValueError(f"a_q5_10 must contain exactly {expected_len} values, got {len(a_vals)}")
    if len(b_vals) != expected_len:
        raise ValueError(f"b_q5_10 must contain exactly {expected_len} values, got {len(b_vals)}")
    return dim, a_vals, b_vals


def render_array(name, dim, values):
    lines = [f"static const uint32_t {name}[TILED_CASE_ELEMS] = {{"]
    for r in range(dim):
        row = values[r * dim : (r + 1) * dim]
        row_words = ", ".join(f"0x{to_u16(v):04x}u" for v in row)
        suffix = "," if r < (dim - 1) else ""
        lines.append(f"    {row_words}{suffix}")
    lines.append("};")
    return "\n".join(lines)


def render_header(case):
    dim, a_vals, b_vals = validate_case(case)
    name = case.get("name", "unknown")
    notes = case.get("notes", "No notes.")
    return "\n".join(
        [
            "/* Auto-generated by gen_tiled_case_header.py */",
            f"/* case: {name} */",
            f"/* notes: {notes} */",
            "",
            f"#define TILED_CASE_DIM {dim}u",
            f"#define TILED_CASE_ELEMS ({dim}u * {dim}u)",
            "",
            render_array("a_init", dim, a_vals),
            "",
            render_array("b_init", dim, b_vals),
            "",
        ]
    )


def main():
    parser = argparse.ArgumentParser(description="Generate tiled_case_data.h for a selected NxN tiled case.")
    parser.add_argument("--cases", required=True, help="Path to tiled case json")
    parser.add_argument("--case", required=True, help="Case name")
    parser.add_argument("--header-out", required=True, help="Output header path")
    args = parser.parse_args()

    case = load_case(args.cases, args.case)
    header_text = render_header(case)
    out_path = Path(args.header_out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header_text, encoding="utf-8")
    print(f"Generated tiled case header for '{args.case}' at {out_path}")


if __name__ == "__main__":
    main()
